Repository aws-controllers-k8s/sqs-controller, pull requests merged in 2023-05, with the labels that each got.

#32 Fix/adopt resource not found
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  generator.yaml
  pkg/resource/queue/hooks.go
  pkg/resource/queue/sdk.go
  templates/hooks/queue/sdk_get_attributes_pre_set_output.go.tpl
  test/e2e/tests/test_queue.py
Labels: approved, lgtm, ok-to-test

#33 Release artifact for release `v1.0.2`
  config/controller/kustomization.yaml
  helm/Chart.yaml
  helm/templates/NOTES.txt
  helm/templates/_helpers.tpl
  helm/templates/deployment.yaml
  helm/values.schema.json
  helm/values.yaml
Labels: approved

#35 Support queues `RedriveAllowPolicy`
  apis/v1alpha1/ack-generate-metadata.yaml
  apis/v1alpha1/generator.yaml
  apis/v1alpha1/queue.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/controller/kustomization.yaml
  config/crd/bases/sqs.services.k8s.aws_queues.yaml
  generator.yaml
  helm/Chart.yaml
  helm/crds/sqs.services.k8s.aws_queues.yaml
  helm/templates/NOTES.txt
  helm/values.yaml
  pkg/resource/queue/delta.go
  pkg/resource/queue/sdk.go
  test/e2e/tests/test_queue.py
Labels: approved, lgtm
